// <auto-generated />
using System;
using BilheteriaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BilheteriaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BilheteriaAPI.Models.Assento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SetorId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SetorId");

                    b.ToTable("Assentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Numero = "A1",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            Numero = "A2",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            Numero = "A3",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            Numero = "A4",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            Numero = "A5",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            Numero = "A6",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            Numero = "A7",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            Numero = "A8",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 9,
                            Numero = "A9",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 10,
                            Numero = "A10",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 11,
                            Numero = "B1",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 12,
                            Numero = "B2",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 13,
                            Numero = "B3",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 14,
                            Numero = "B4",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 15,
                            Numero = "B5",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 16,
                            Numero = "B6",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 17,
                            Numero = "B7",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 18,
                            Numero = "B8",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 19,
                            Numero = "B9",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 20,
                            Numero = "B10",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 21,
                            Numero = "C1",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 22,
                            Numero = "C2",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 23,
                            Numero = "C3",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 24,
                            Numero = "C4",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 25,
                            Numero = "C5",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 26,
                            Numero = "C6",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 27,
                            Numero = "C7",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 28,
                            Numero = "C8",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 29,
                            Numero = "C9",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 30,
                            Numero = "C10",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 31,
                            Numero = "D1",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 32,
                            Numero = "D2",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 33,
                            Numero = "D3",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 34,
                            Numero = "D4",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 35,
                            Numero = "D5",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 36,
                            Numero = "D6",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 37,
                            Numero = "D7",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 38,
                            Numero = "D8",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 39,
                            Numero = "D9",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 40,
                            Numero = "D10",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 41,
                            Numero = "E1",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 42,
                            Numero = "E2",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 43,
                            Numero = "E3",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 44,
                            Numero = "E4",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 45,
                            Numero = "E5",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 46,
                            Numero = "E6",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 47,
                            Numero = "E7",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 48,
                            Numero = "E8",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 49,
                            Numero = "E9",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 50,
                            Numero = "E10",
                            SetorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 51,
                            Numero = "A1",
                            SetorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 52,
                            Numero = "A2",
                            SetorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 53,
                            Numero = "A3",
                            SetorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 54,
                            Numero = "A4",
                            SetorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 55,
                            Numero = "A5",
                            SetorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 56,
                            Numero = "A6",
                            SetorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 57,
                            Numero = "A7",
                            SetorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 58,
                            Numero = "A8",
                            SetorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 59,
                            Numero = "A9",
                            SetorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 60,
                            Numero = "A10",
                            SetorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 61,
                            Numero = "B1",
                            SetorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 62,
                            Numero = "B2",
                            SetorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 63,
                            Numero = "B3",
                            SetorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 64,
                            Numero = "B4",
                            SetorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 65,
                            Numero = "B5",
                            SetorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 66,
                            Numero = "B6",
                            SetorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 67,
                            Numero = "B7",
                            SetorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 68,
                            Numero = "B8",
                            SetorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 69,
                            Numero = "B9",
                            SetorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 70,
                            Numero = "B10",
                            SetorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 71,
                            Numero = "A1",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 72,
                            Numero = "A2",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 73,
                            Numero = "A3",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 74,
                            Numero = "A4",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 75,
                            Numero = "A5",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 76,
                            Numero = "A6",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 77,
                            Numero = "A7",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 78,
                            Numero = "A8",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 79,
                            Numero = "A9",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 80,
                            Numero = "A10",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 81,
                            Numero = "B1",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 82,
                            Numero = "B2",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 83,
                            Numero = "B3",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 84,
                            Numero = "B4",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 85,
                            Numero = "B5",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 86,
                            Numero = "B6",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 87,
                            Numero = "B7",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 88,
                            Numero = "B8",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 89,
                            Numero = "B9",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 90,
                            Numero = "B10",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 91,
                            Numero = "C1",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 92,
                            Numero = "C2",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 93,
                            Numero = "C3",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 94,
                            Numero = "C4",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 95,
                            Numero = "C5",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 96,
                            Numero = "C6",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 97,
                            Numero = "C7",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 98,
                            Numero = "C8",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 99,
                            Numero = "C9",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 100,
                            Numero = "C10",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 101,
                            Numero = "D1",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 102,
                            Numero = "D2",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 103,
                            Numero = "D3",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 104,
                            Numero = "D4",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 105,
                            Numero = "D5",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 106,
                            Numero = "D6",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 107,
                            Numero = "D7",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 108,
                            Numero = "D8",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 109,
                            Numero = "D9",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 110,
                            Numero = "D10",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 111,
                            Numero = "E1",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 112,
                            Numero = "E2",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 113,
                            Numero = "E3",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 114,
                            Numero = "E4",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 115,
                            Numero = "E5",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 116,
                            Numero = "E6",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 117,
                            Numero = "E7",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 118,
                            Numero = "E8",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 119,
                            Numero = "E9",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 120,
                            Numero = "E10",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 121,
                            Numero = "F1",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 122,
                            Numero = "F2",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 123,
                            Numero = "F3",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 124,
                            Numero = "F4",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 125,
                            Numero = "F5",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 126,
                            Numero = "F6",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 127,
                            Numero = "F7",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 128,
                            Numero = "F8",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 129,
                            Numero = "F9",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 130,
                            Numero = "F10",
                            SetorId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 131,
                            Numero = "A1",
                            SetorId = 4,
                            Status = 0
                        },
                        new
                        {
                            Id = 132,
                            Numero = "A2",
                            SetorId = 4,
                            Status = 0
                        },
                        new
                        {
                            Id = 133,
                            Numero = "A3",
                            SetorId = 4,
                            Status = 0
                        },
                        new
                        {
                            Id = 134,
                            Numero = "A4",
                            SetorId = 4,
                            Status = 0
                        },
                        new
                        {
                            Id = 135,
                            Numero = "A5",
                            SetorId = 4,
                            Status = 0
                        },
                        new
                        {
                            Id = 136,
                            Numero = "A6",
                            SetorId = 4,
                            Status = 0
                        },
                        new
                        {
                            Id = 137,
                            Numero = "A7",
                            SetorId = 4,
                            Status = 0
                        },
                        new
                        {
                            Id = 138,
                            Numero = "A8",
                            SetorId = 4,
                            Status = 0
                        },
                        new
                        {
                            Id = 139,
                            Numero = "A9",
                            SetorId = 4,
                            Status = 0
                        },
                        new
                        {
                            Id = 140,
                            Numero = "A10",
                            SetorId = 4,
                            Status = 0
                        },
                        new
                        {
                            Id = 141,
                            Numero = "B1",
                            SetorId = 4,
                            Status = 0
                        },
                        new
                        {
                            Id = 142,
                            Numero = "B2",
                            SetorId = 4,
                            Status = 0
                        },
                        new
                        {
                            Id = 143,
                            Numero = "B3",
                            SetorId = 4,
                            Status = 0
                        },
                        new
                        {
                            Id = 144,
                            Numero = "B4",
                            SetorId = 4,
                            Status = 0
                        },
                        new
                        {
                            Id = 145,
                            Numero = "B5",
                            SetorId = 4,
                            Status = 0
                        },
                        new
                        {
                            Id = 146,
                            Numero = "A1",
                            SetorId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 147,
                            Numero = "A2",
                            SetorId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 148,
                            Numero = "A3",
                            SetorId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 149,
                            Numero = "A4",
                            SetorId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 150,
                            Numero = "A5",
                            SetorId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 151,
                            Numero = "A6",
                            SetorId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 152,
                            Numero = "A7",
                            SetorId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 153,
                            Numero = "A8",
                            SetorId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 154,
                            Numero = "A9",
                            SetorId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 155,
                            Numero = "A10",
                            SetorId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 156,
                            Numero = "B1",
                            SetorId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 157,
                            Numero = "B2",
                            SetorId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 158,
                            Numero = "B3",
                            SetorId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 159,
                            Numero = "B4",
                            SetorId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 160,
                            Numero = "B5",
                            SetorId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 161,
                            Numero = "B6",
                            SetorId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 162,
                            Numero = "B7",
                            SetorId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 163,
                            Numero = "B8",
                            SetorId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 164,
                            Numero = "B9",
                            SetorId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 165,
                            Numero = "B10",
                            SetorId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 166,
                            Numero = "C1",
                            SetorId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 167,
                            Numero = "C2",
                            SetorId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 168,
                            Numero = "C3",
                            SetorId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 169,
                            Numero = "C4",
                            SetorId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 170,
                            Numero = "C5",
                            SetorId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 171,
                            Numero = "C6",
                            SetorId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 172,
                            Numero = "C7",
                            SetorId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 173,
                            Numero = "C8",
                            SetorId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 174,
                            Numero = "C9",
                            SetorId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 175,
                            Numero = "C10",
                            SetorId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 176,
                            Numero = "D1",
                            SetorId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 177,
                            Numero = "D2",
                            SetorId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 178,
                            Numero = "D3",
                            SetorId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 179,
                            Numero = "D4",
                            SetorId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 180,
                            Numero = "D5",
                            SetorId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 181,
                            Numero = "D6",
                            SetorId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 182,
                            Numero = "D7",
                            SetorId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 183,
                            Numero = "D8",
                            SetorId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 184,
                            Numero = "D9",
                            SetorId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 185,
                            Numero = "D10",
                            SetorId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 186,
                            Numero = "A1",
                            SetorId = 6,
                            Status = 0
                        },
                        new
                        {
                            Id = 187,
                            Numero = "A2",
                            SetorId = 6,
                            Status = 0
                        },
                        new
                        {
                            Id = 188,
                            Numero = "A3",
                            SetorId = 6,
                            Status = 0
                        },
                        new
                        {
                            Id = 189,
                            Numero = "A4",
                            SetorId = 6,
                            Status = 0
                        },
                        new
                        {
                            Id = 190,
                            Numero = "A5",
                            SetorId = 6,
                            Status = 0
                        },
                        new
                        {
                            Id = 191,
                            Numero = "A6",
                            SetorId = 6,
                            Status = 0
                        },
                        new
                        {
                            Id = 192,
                            Numero = "A7",
                            SetorId = 6,
                            Status = 0
                        },
                        new
                        {
                            Id = 193,
                            Numero = "A8",
                            SetorId = 6,
                            Status = 0
                        },
                        new
                        {
                            Id = 194,
                            Numero = "A9",
                            SetorId = 6,
                            Status = 0
                        },
                        new
                        {
                            Id = 195,
                            Numero = "A10",
                            SetorId = 6,
                            Status = 0
                        },
                        new
                        {
                            Id = 196,
                            Numero = "B1",
                            SetorId = 6,
                            Status = 0
                        },
                        new
                        {
                            Id = 197,
                            Numero = "B2",
                            SetorId = 6,
                            Status = 0
                        },
                        new
                        {
                            Id = 198,
                            Numero = "B3",
                            SetorId = 6,
                            Status = 0
                        },
                        new
                        {
                            Id = 199,
                            Numero = "B4",
                            SetorId = 6,
                            Status = 0
                        },
                        new
                        {
                            Id = 200,
                            Numero = "B5",
                            SetorId = 6,
                            Status = 0
                        },
                        new
                        {
                            Id = 201,
                            Numero = "B6",
                            SetorId = 6,
                            Status = 0
                        },
                        new
                        {
                            Id = 202,
                            Numero = "B7",
                            SetorId = 6,
                            Status = 0
                        },
                        new
                        {
                            Id = 203,
                            Numero = "B8",
                            SetorId = 6,
                            Status = 0
                        },
                        new
                        {
                            Id = 204,
                            Numero = "B9",
                            SetorId = 6,
                            Status = 0
                        },
                        new
                        {
                            Id = 205,
                            Numero = "B10",
                            SetorId = 6,
                            Status = 0
                        });
                });

            modelBuilder.Entity("BilheteriaAPI.Models.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Eventos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Data = new DateTime(2025, 8, 15, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "O maior show de rock do ano com bandas internacionais!",
                            ImagemUrl = "🎸",
                            Local = "Arena Unifeso",
                            Nome = "Show de Rock 2024"
                        },
                        new
                        {
                            Id = 2,
                            Data = new DateTime(2025, 9, 5, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Uma noite inesquecível com os melhores DJs do mundo",
                            ImagemUrl = "🎧",
                            Local = "Clube Teresópolis",
                            Nome = "Festival de Música Eletrônica"
                        },
                        new
                        {
                            Id = 3,
                            Data = new DateTime(2025, 7, 20, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Peça clássica de Shakespeare com elenco renomado",
                            ImagemUrl = "🎭",
                            Local = "Teatro Municipal",
                            Nome = "Teatro: A Comédia dos Erros"
                        });
                });

            modelBuilder.Entity("BilheteriaAPI.Models.Ingresso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssentoId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoUnico")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssentoId");

                    b.HasIndex("CodigoUnico")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("Ingressos");
                });

            modelBuilder.Entity("BilheteriaAPI.Models.Setor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("QuantidadeDisponivel")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeTotal")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.ToTable("Setores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventoId = 1,
                            Nome = "Pista",
                            Preco = 80.00m,
                            QuantidadeDisponivel = 50,
                            QuantidadeTotal = 50
                        },
                        new
                        {
                            Id = 2,
                            EventoId = 1,
                            Nome = "Camarote",
                            Preco = 200.00m,
                            QuantidadeDisponivel = 20,
                            QuantidadeTotal = 20
                        },
                        new
                        {
                            Id = 3,
                            EventoId = 2,
                            Nome = "Pista",
                            Preco = 100.00m,
                            QuantidadeDisponivel = 60,
                            QuantidadeTotal = 60
                        },
                        new
                        {
                            Id = 4,
                            EventoId = 2,
                            Nome = "VIP",
                            Preco = 250.00m,
                            QuantidadeDisponivel = 15,
                            QuantidadeTotal = 15
                        },
                        new
                        {
                            Id = 5,
                            EventoId = 3,
                            Nome = "Plateia",
                            Preco = 60.00m,
                            QuantidadeDisponivel = 40,
                            QuantidadeTotal = 40
                        },
                        new
                        {
                            Id = 6,
                            EventoId = 3,
                            Nome = "Balcão",
                            Preco = 40.00m,
                            QuantidadeDisponivel = 20,
                            QuantidadeTotal = 20
                        });
                });

            modelBuilder.Entity("BilheteriaAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@bilheteria.com",
                            Nome = "Administrador",
                            SenhaHash = "$2a$11$Sj6FFqXRMKbqptoNe8/ESuTzs5q2ar5H2NrCBsw4TBfUka1eGXosm",
                            Tipo = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "cliente@email.com",
                            Nome = "Cliente Teste",
                            SenhaHash = "$2a$11$pUX86BEuYqjBB.AU/12rnOv.u3R7YWB5.e8ndOI8g6noHjnO66Ruq",
                            Tipo = "Cliente"
                        });
                });

            modelBuilder.Entity("BilheteriaAPI.Models.Assento", b =>
                {
                    b.HasOne("BilheteriaAPI.Models.Setor", "Setor")
                        .WithMany("Assentos")
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("BilheteriaAPI.Models.Ingresso", b =>
                {
                    b.HasOne("BilheteriaAPI.Models.Assento", "Assento")
                        .WithMany()
                        .HasForeignKey("AssentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BilheteriaAPI.Models.Usuario", "Usuario")
                        .WithMany("Ingressos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BilheteriaAPI.Models.Setor", b =>
                {
                    b.HasOne("BilheteriaAPI.Models.Evento", "Evento")
                        .WithMany("Setores")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("BilheteriaAPI.Models.Evento", b =>
                {
                    b.Navigation("Setores");
                });

            modelBuilder.Entity("BilheteriaAPI.Models.Setor", b =>
                {
                    b.Navigation("Assentos");
                });

            modelBuilder.Entity("BilheteriaAPI.Models.Usuario", b =>
                {
                    b.Navigation("Ingressos");
                });
#pragma warning restore 612, 618
        }
    }
}
